swagger: '2.0'
info:
  version: 1.0.0
  title: Motcert Web Server
  contact:
    email: guolidong@chainnova.com
host: 23.91.102.163
basePath: /v1
tags:
  - name: motcert
schemes:
  - https
  - http
paths:
  /certificate:
    post:
      tags:
        - certificate
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Certificate object that needs to be added to the block chain
          required: true
          schema:
            $ref: '#/definitions/Certificate'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Result'
        '400':
          description: Invalid input
        '404':
          description: Not found
        '405':
          description: Validation exception
  '/certificate/{certId}':
    get:
      tags:
        - certificate
      summary: Finds Certificate by CertId
      produces:
        - application/xml
        - application/json
      parameters:
        - name: certId
          in: path
          type: string
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Certificate'
        '400':
          description: Invalid input
        '404':
          description: Cert not found
  /openStatus:
    post:
      tags:
        - certificate
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Status'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Result'
        '400':
          description: Invalid input
        '404':
          description: Not found
        '405':
          description: Validation exception
  /certificate/queryList:
    post:
      tags:
        - certificate
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/QueryConditions'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/MetaData'
        '400':
          description: Invalid input
        '404':
          description: Not found
  /certificate/queryListByPage:
    get:
      tags:
        - certificate
      produces:
        - application/xml
        - application/json
      parameters:
        - name: bookmark
          in: query
          type: string
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Certificate'
        '400':
          description: Invalid input
        '404':
          description: Certs not found
  /login:
    post:
      tags:
        - login
      summary: Logs user into the system
      description: ''
      operationId: loginUser
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Result'
        '400':
          description: Invalid input
        '404':
          description: Not found
        '405':
          description: Validation exception
  /logout:
    post:
      tags:
        - logout
      summary: Logs out current logged in user session
      description: ''
      operationId: logoutUser
      produces:
        - application/xml
        - application/json
      parameters: []
      responses:
        default:
          description: successful operation
definitions:
  Result:
    type: object
    properties:
      resultCode:
        type: integer
      message:
        type: string
      data:
        type: object
  User:
    type: object
    properties:
      name:
        type: string
      password:
        type: string
  Certificate:
    type: object
    properties:
      certId:
        type: string
        description: 证书编号
      certType:
        type: string
        description: 证书类型
      entrustOrg:
        type: string
        description: 委托单位
      instrumentName:
        type: string
        description: 器具名称
      spec:
        type: string
        description: 型号/规格
      exportId:
        type: string
        description: 出厂编号
      madeByOrg:
        type: string
        description: 制造单位
      entrustOrgAdd:
        type: string
        description: 委托单位地址
      approver:
        type: string
        description: 批准人
      verifier:
        type: string
        description: 核验员
      calibratePerson:
        type: string
        description: 校准员
      calibrateDate:
        type: string
        description: 校准日期
        format: string-date
      suggestNextCaliDate:
        type: string
        description: 建议下次校准日期
        format: string-date
      isCompleted:
        type: boolean
        description: 当前证书是否已经录入完成
      isOpen:
        type: boolean
        description: 当前证书是否是公开状态
      isDeleted:
        type: boolean
        description: 当前证书是否是已删除状态
  Status:
    type: object
    properties:
      certId:
        type: string
      isOpen:
        type: boolean
      isChangedOnChain:
        type: boolean
  MetaData:
    type: object
    properties:
      pageCount:
        type: integer
      bookmarks:
        type: array
        items:
          $ref: '#/definitions/Bookmark'
      certs:
        type: array
        items:
          $ref: '#/definitions/Certificate'
  Bookmark:
    type: object
    properties:
      pageIndex:
        type: integer
      bookmark:
        type: string
  QueryConditions:
    type: object
    properties:
      pageSize:
        type: integer
        description: 每页数据量
      pageIndex:
        type: integer
        description: 本次请求的页码
      isOpen:
        type: boolean
        description: 是否公开
      isCompleted:
        type: boolean
        description: 是否完成
      isDeleted:
        type: boolean
        description: 是否删除
      certType:
        type: string
        description: 证书类型
      certId:
        type: string
        description: 证书编号
      entrustOrg:
        type: string
        description: 委托单位
      instrumentName:
        type: string
        description: 器具名称
      startCreateDate:
        type: string
        description: 起始录入日期
      endCreateDate:
        type: string
        description: 结束录入日期
      startCalibDate:
        type: string
        description: 起始校准日期
      endCalibDate:
        type: string
        description: 结束校准日期
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
